name: Build

on:
  push:
    branches: [ "glass" ]
  pull_request:
    branches: [ "glass" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .\WinCenterTitle.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Build funchook
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
           cd .\libs\funchook 
           md build
           cd build
           dir
           cmake -G "Visual Studio 16 2019" -A x64 ..
           cmake --build . --config Release

    - name: Build WinCenterTitle
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /property:Platform=x64

    - name: Upload WinCenterTitle
      uses: actions/upload-artifact@v3
      with:
        # Artifact name
        name: WinCenterTitle
        # A file, directory or wildcard pattern that describes what to upload
        path: x64/Release/*
